### ISSUE TITLE
undefined method artist for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by galaris** [bogem/nehm#1]
USER:nehm user$ nehm get 100 posts
Getting information about track(s)
Was skipped 79 playlist(s) (nehm doesn't download playlists)

_... downloads a few songs successfully..._

Downloading clammyclams - 05 Lvl [A$AP Rocky]
###### ################################################################## 100.0%

Downloading artwork
###### ################################################################## 100.0%

Setting tags
/Library/Ruby/Gems/2.0.0/gems/nehm-1.5.5.2/lib/nehm/get.rb:84:in `block in tag': undefined method`artist=' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/taglib-ruby-0.7.0/lib/taglib/base.rb:8:in `open'
    from /Library/Ruby/Gems/2.0.0/gems/nehm-1.5.5.2/lib/nehm/get.rb:81:in`tag'
    from /Library/Ruby/Gems/2.0.0/gems/nehm-1.5.5.2/lib/nehm/get.rb:54:in `block in []'
    from /Library/Ruby/Gems/2.0.0/gems/nehm-1.5.5.2/lib/nehm/get.rb:50:in`each'
    from /Library/Ruby/Gems/2.0.0/gems/nehm-1.5.5.2/lib/nehm/get.rb:50:in `[]'
    from /Library/Ruby/Gems/2.0.0/gems/nehm-1.5.5.2/lib/nehm.rb:28:in`do'
    from /Library/Ruby/Gems/2.0.0/gems/nehm-1.5.5.2/bin/nehm:6:in `<top (required)>'
    from /usr/bin/nehm:23:in`load'
    from /usr/bin/nehm:23:in `<main>'

USER:nehm user$

**Comment by n10v** [comment]
Can you post the link on this track, please?

**Comment by n10v** [comment]
Already found link on this track
(Btw Clams Casino - awesome producer👍)

**Comment by n10v** [comment]
Thanks for the issue!
