### ISSUE TITLE
nehm sync does only sync 270 of my ~620 likes

### ISSUE THREAD

**Issue by Snake4life** [bogem/nehm#17]
nehm sync does only sync 270 of my ~620 likes

https://soundcloud.com/snake4life/likes

**Comment by n10v** [comment]
SoundCloud API sends 403 Forbidden response, if you want to receive 369th (limit=150&offset=200) and more track.
I think, user should have auth token to access more than 369 likes.

**Comment by n10v** [comment]
Related to #14

**Comment by Snake4life** [comment]
Oh, I've already thought so

**Comment by n10v** [comment]
Sorry, but I will solve this problem in one-two weeks, because I have a lot of work now.

**Comment by Snake4life** [comment]
Sure no problem! Great work so far thank you very very much 👍

**Comment by n10v** [comment]
Authorization didn't help: I always become 403 when trying to get more than 300 likes. 
Besides I didn't find an answer in google, so I asked a question at [StackOverflow](https://stackoverflow.com/questions/43940103/how-to-get-more-than-350-favorites-with-soundcloud-api) (second time in my life).

**Comment by n10v** [comment]
There is an [answer](http://stackoverflow.com/a/44068861/4842868) on StackOverflow! We don't need an authorization: we can use paginator, that can access without authorization to tracks we need.

**Comment by n10v** [comment]
Some progress:
![2017-05-20 13 12 02](https://cloud.githubusercontent.com/assets/13235519/26275327/031570e8-3d5e-11e7-9785-389925ca4c02.png)

**Comment by n10v** [comment]
So I fixed it in https://github.com/bogem/nehm/commit/29cb18cc4c702fb8cd3157eda58e44d6ec35f088.
Please test it.
