### ISSUE TITLE
doesn’t understand the “add” message. (-1708)

### ISSUE THREAD

**Issue by galaris** [bogem/nehm#2]
The error message in the title appeared for each downloaded song.

USER:nehm user$ nehm get 100 posts

Downloading BLVCK CEILING - bombay
###### ################################################################## 100.0%

Downloading artwork
###### ################################################################## 100.0%

Setting tags
Adding to iTunes
/Library/Ruby/Gems/2.0.0/gems/nehm-1.5.5.2/lib/nehm/applescripts/add_track_to_playlist.applescript:170:200: execution error: iTunes got an error: file "Macintosh HD:Users:user:Downloads:~Soundcloud:download2:BLVCK CEILING - bombay.mp3" doesn’t understand the “add” message. (-1708)

USER:nehm user$ 

ITunes v12.3.0.44 on Yosemite 10.10.3.

**Comment by n10v** [comment]
I know this bug
Working on it
