### ISSUE TITLE
[Request] Add Image to downloaded Trackfile

### ISSUE THREAD

**Issue by Snake4life** [bogem/nehm#22]
Hi,

my suggestion would be to download the 500x500 image from the song and add it into the .mp3 file, looks like this:

![image](https://user-images.githubusercontent.com/13849408/54884240-e5c87700-4e6e-11e9-8167-d45dd473f5f1.png)

**Comment by n10v** [comment]
Actually nehm already downloads 500x500 artwork and sets it to track. Try to open the track with a media player and most likely you see the artwork.

If you interested, you can see the code here: https://github.com/bogem/nehm/blob/master/track/track.go#L40.

**Comment by Snake4life** [comment]
thanks for the quick answer, looks like windows 10 and Groove Music Player cant handle the cover, vlc just works fine :)

thanks for the greate software and the client id update, old one was really crowded

**Comment by n10v** [comment]
There was also an issue with it on mac: https://github.com/bogem/id3v2/issues/31#issuecomment-353428748.

> thanks for the greate software and the client id update, old one was really crowded

Yes, I couldn't use nehm with old clientID 🤒
