### ISSUE TITLE
no implicit conversion of Hash into Array

### ISSUE THREAD

**Issue by galaris** [bogem/nehm#3]
Getting the following error when trying to get my likes:

foo:bin bar$ ./nehm dl 876 likes
While executing nehm ... (TypeError)
    no implicit conversion of Hash into Array

Additionally the like number param does not seem to be working:

foo:bin bar$ ./nehm dl likes 900
Invalid argument/option '900'
foo:bin bar$ ./nehm dl likes 880
Invalid argument/option '880'
foo:bin bar$ ./nehm dl likes 200
Invalid argument/option '200'
foo:bin bar$ ./nehm dl likes 100
Invalid argument/option '100'
foo:bin bar$ ./nehm dl likes 30
Invalid argument/option '30'
foo:bin bar$ ./nehm dl likes 1
Invalid argument/option '1'
foo:bin bar$ ./nehm dl likes
Invalid limit value
It should be more than 0
foo:bin bar$

**Comment by bogem** [comment]
You should write number of likes before the word "likes"
For example, 'nehm dl 300 likes'

**Comment by bogem** [comment]
What version of nehm you use?

**Comment by n10v** [comment]
Hm. This bug reproducts, if you have less likes than you inputed in nehm
Thanks for report. I will fix it soon

**Comment by n10v** [comment]
And you must always write count the number of likes before the word "likes"

**Comment by n10v** [comment]
Fixed
Thanks for report!
