### ISSUE TITLE
couldn't unmarshal the config file: yaml: line 1: did not find expected hexdecimal number

### ISSUE THREAD

**Issue by redwards510** [bogem/nehm#4]
OS: windows 10

command executed: 
nehm get https://soundcloud.com/ashatack/28th-july-the-just-on-track-showcase-with-ashatack-2016

error message: 
couldn't unmarshal the config file: yaml: line 1: did not find expected hexdecimal number

contents of .nehmconfig file:

permalink: "krakenskulls"
dl_folder: "c:\users\ryan\music"

**Comment by n10v** [comment]
It seems that you have extra spaces in your nehm config file: https://github.com/tenderlove/psych/issues/190#issuecomment-162658663

Try to delete all possible extra spaces in your nehm config
Or try to just copy-paste these lines:

```
permalink: krakenskulls
dl_folder: c:\users\ryan\music
```

**Comment by redwards510** [comment]
Interesting. You are right, there were some trailing spaces after the values and before the newlines. Now when I execute the same command, I get this:

> Downloading 28th July -The Just On Track Showcase With Ashatack - 2016
> download failed: exec: "curl": executable file not found in %!P(MISSING)ATH%!(NOVERB)

But that is a separate issue I suppose.

**Comment by n10v** [comment]
@redwards510 yes, it is exactly separate issue. On `windows` there are no pre-installed `curl` command. That's why this bug occurs. 
Try to install `curl` like [here](http://stackoverflow.com/a/16216825)

**Comment by redwards510** [comment]
@bogem I do have curl installed in my path though... I'm not sure what %!P(MISSING)ATH%!(NOVERB) is though.

**Comment by n10v** [comment]
I'm also don't know what it is. I think, in future releases I will remove dependency from `curl` and build in my own tiny downloader.
