### ISSUE TITLE
command line flags don't work in windows. 

### ISSUE THREAD

**Issue by redwards510** [bogem/nehm#5]
command executed:
nehm -f "C:\users\ryan\music" -p "krakenskulls" get https://soundcloud.com/ashatack/28th-july-the-just-on-track-showcase-with-ashatack-2016

error message: 
You didn't set a permalink. Use flag '-f' or set permalink in config file.

Obviously, I did set -f

**Comment by n10v** [comment]
Thanks for bug report. I know the reason of this bug and I will fix it today or tomorrow.

**Comment by n10v** [comment]
Fixed in [3.0.1](https://github.com/bogem/nehm/releases/tag/v3.0.1) version
