### ISSUE TITLE
Get all likes of "username" and download only new likes that arent in folder "foldername" downloaded already

### ISSUE THREAD

**Issue by Snake4life** [bogem/nehm#8]
Hey thank you very much this software works great!

How can I accomplish my subject?
I want to trigger a cronjob everyday to sync my soundcloud likes to my plex library

**Comment by n10v** [comment]
Thank you for a feature proposing!
I thought about it some time and I have an idea, how I would implement it.
I'd like to add new command called `nehm sync`. This command will:
1. Get all likes of user
2. Get all tracks in folder
3. Compare them
4. Download missing tracks to folder

What do you think of it?

**Comment by Snake4life** [comment]
point 3: skip track if it has been converted to a 30seconds preview aka. has been gone to soundcloud g o only, mostly these tracks are only 400kb big in size.

point 4.5: command: nehm sync --no-preview do not download likes that are previews of songs which you need soundcloud go to listen to the full track

thank you very very much!

**Comment by n10v** [comment]
Cool, but I have one question:

> point 3: skip track if it has been converted to a 30seconds preview aka. has been gone to soundcloud g o only, mostly these tracks are only 400kb big in size.

Do you mean, what `nehm sync` should skip track if this **track in folder** is a 30 second preview?

**Comment by Snake4life** [comment]
uhm sometimes a full track is getting disabled and only a 30 seconds preview is available, which means you have to buy soundcloud go to listen to the full version again. Lets say we were lucky and did a `nehm sync` before it went into a soundcloud go only track, so nehm will just skip this 30seconds preview, basically 3 and 4.5 is the same :D

**Comment by n10v** [comment]
Some information about `--no-preview` flag: SoundCloud API doesn't send track if it is SoundCloud Go preview, so user always becomes no preview, normal tracks. Therefore I will not implement this flag.

**Comment by n10v** [comment]
@Snake4life Please test!
